# Generated by Django 5.0.6 on 2024-06-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
