# Generated by Django 5.0.6 on 2024-06-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0017_remove_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
