# Generated by Django 5.0.6 on 2024-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0018_remove_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('blog', 'blog'), ('ripetizioni', 'ripetizioni'), ('libri/appunti', 'libri/appunti'), ('news', 'news'), ('spotted', 'spotted'), ('esami', 'esami')], max_length=255, null=True),
        ),
    ]
