# Generated by Django 5.0.6 on 2024-06-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0019_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('blog', 'blog'), ('esami', 'esami'), ('libri/appunti', 'libri/appunti'), ('news', 'news'), ('blog', 'blog'), ('ripetizioni', 'ripetizioni')], max_length=255, null=True),
        ),
    ]
