# Generated by Django 5.0.6 on 2024-06-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0021_rename_twitter_url_profile_città_profile_età_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='età',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
