# Generated by Django 5.0.6 on 2024-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0022_alter_profile_età'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('blog', 'blog'), ('esami', 'esami'), ('libri/appunti', 'libri/appunti'), ('news', 'news'), ('blog', 'blog'), ('ripetizioni', 'ripetizioni')], default='blog', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
