# Generated by Django 5.0.6 on 2024-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0023_alter_post_category_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('blog', 'blog'), ('esami', 'esami'), ('libri/appunti', 'libri/appunti'), ('news', 'news'), ('ripetizioni', 'ripetizioni')], default='blog', max_length=255),
        ),
    ]
