# Generated by Django 5.0.6 on 2024-06-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0025_remove_comment_name_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('blog', 'blog'), ('esami', 'esami'), ('libri/appunti', 'libri/appunti'), ('news', 'news'), ('ripetizioni', 'ripetizioni')], max_length=255, unique=True),
        ),
    ]
