# Generated by Django 5.0.6 on 2024-06-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elaboratoPPM', '0027_alter_category_name_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='blog', max_length=255),
        ),
    ]
